### PR TITLE
Add Phrase support

### PR DESCRIPTION
**Pull request by czkoko**
Add Phrase support.
new func : NewPhraseListGrammarFromRecognizer, AddPhrase, Clear

### CODE REVIEW

**Review by czkoko — COMMENTED** [review]
Modify error display

**Comment by konsti** [comment]
Is there any chance this is merged soon? We would like to use it with our implementation as well.

**Comment by mcilibrizzi** [comment]
Having Phrase List Grammar feature will be really helpful for our project as well

**Comment by glecaros** [comment]
@czkoko thank you for creating this PR!

**Review by trrwilson — APPROVED** [review]

**Pull request merged**
